Add files via upload

diff --git a/kernel-install b/kernel-install
--- a/kernel-install
+++ b/kernel-install
@@ -10,6 +10,11 @@ fi
 version_str=$1
 if [ -z "$1" ]; then
 	version_str=$(curl -sL 'https://api.github.com/repos/javidizadi/linux-cachyos/releases/latest' | jq -r ".tag_name")
+	if [ "$version_str" = 'null' ]; then
+		echo "Failed to get latest version."
+		exit 2
+	fi
+
 	echo "Installing the latest version ( ${version_str} )"
 fi
 
